### ISSUE TITLE
Talk Idea: Docker

### ISSUE THREAD

**Issue by swhalley** [peidevs/Event_Resources#27]
Submitted By : Sean Whalley
A beginner's guide to docker. Many talks I have been to expect a certain knowledge of all the docker verbiage and miss most of the good stuff. 

Showing how to run docker and setup not just a development environment, but showing how that container can be moved away from the developer machine and to a QA system

**Comment by jpatters** [comment]
I think we could do a whole series on docker. 
- Beginner Docker
- Docker for development
- Docker in production
- Docker swarm
- Docker cloud
- Continuous delivery and docker
- CoreOS
- etc

There is a tonne of stuff that could be talked about. Maybe each talk requires that you have the knowledge from Beginner Docker?

**Comment by swhalley** [comment]
I would lean more towards getting a talk out about Docker for Development as a beginner talk.
Seeing how someone sets up their development environment. A few question I have are
1. Do you pull the latest code as part of the init process, map a drive and point your IDE into the docker container?
2. Do you map a drive and keep the source local, and have the map into the docker container?

From what I read their isn't a norm. People are still trying to figure out best practices for a lot of things.

**Comment by jpatters** [comment]
I always map a drive and keep the source local. But I rarely use docker to develop on. In my opinion, docker is only efficient for development if you are deving on linux. Maybe I'm just whiney, but the mounted volume in a VM is too slow for me to work efficiently. And the new docker for mac/windows has been even slower. 
Because of this, I use docker in development for supporting applications. redis, postgres, background workers, etc.
/sidebar

But yes, best practices would be good as well.

**Comment by codetojoy** [comment]
Please see [issue 31](https://github.com/peidevs/Event_Resources/issues/31) for an upcoming talk in September re: Docker for Beginners. Kevin K is looking for input.

I'm +1 on a series of Docker talks, but IMHO, we should start with the basics to establish common ground. Derek's talk included Docker, Vagrant, and CI; it was great, but spoke to the impact on dev teams rather than an intro to Docker.

**Comment by swhalley** [comment]
closing as duplicate of #31
